### ISSUE TITLE
App crashes when pressing fullscreen

### ISSUE THREAD

**Issue by Cha0sX** [sarbagyastha/youtube_player#15]
If set a GlobalKey to the Widget, App will crash when pressing fullscreen.
```
A VideoPlayerController was used after being disposed.
    Once you have called dispose() on a VideoPlayerController, it can no longer be used.
    #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:108:9)
    #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:114:6)
    #2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:169:12)
    #3      _VideoPlayerState.deactivate (package:youtube_player/youtube_player.dart:523:23)
    #4      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:3893:12)
    #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1727:13)
    #6      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
    #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
    #8      SingleChildRenderObjectElement.
```

**Comment by sarbagyastha** [comment]
@Cha0sX can you post the code snippet of your implementation of the plugin. Didn't get you properly.

**Comment by Cha0sX** [comment]
@sarbagyastha You can reproduce the crash in the example, set a GlobalKey to the parent widget of YoutubePlayer
```
        body: SingleChildScrollView(
          child: Column(
+          key: new GlobalKey(),
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              YoutubePlayer(
                source: id,
                quality: YoutubeQuality.HD,
                callbackController: (controller) {
                  _controller = controller;
                },
              ),
```

**Comment by sarbagyastha** [comment]
@Cha0sX will look into the issue.

**Comment by asapJ** [comment]
Noticed this too

**Comment by asapJ** [comment]
Once full screen is clicked, it gives that error
