### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by justinmccombs** [sarbagyastha/youtube_player#23]
When trying to implement this plugin I get the following error:

```
MissingPluginException(No implementation found for method keepOn on channel sarbagyastha.com.np/youtubePlayer)

#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      YoutubePlayer.keepOn (package:youtube_player/youtube_player.dart:745:45)
#2      _YoutubePlayerState.build (package:youtube_player/youtube_player.dart:830:21)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
#8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
#9      Element.updateChild (package:flutte<…>
[VERBOSE-2:shell.cc(178)] Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method create on channel sarbagyastha.com.np/youtubePlayer)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      VideoPlayerController.initialize (package:youtube_player/youtube_player.dart:214:59)
<asynchronous suspension>
#2      _YoutubePlayerState.initializeYTController (package:youtube_player/youtube_player.dart:799:22)
#3      _YoutubePlayerState.build (package:youtube_player/youtube_player.dart:841:11)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
```

This is with plugin version 3.2.0 on a fresh project where this is the only extra dependency.  Code looks as follows:

```
import 'package:flutter/material.dart';
import 'package:youtube_player/youtube_player.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        title: Text('Test YT'),
      ),
      body: Center(
        child: YoutubePlayer(
          context: context,
          source: "https://www.youtube.com/watch?v=501-0od08t8",
          quality: YoutubeQuality.HD,
        ),
      ),
    );
  }
}
```
I have also used just the video id.

**Comment by sarbagyadhaubanjar** [comment]
@laravelian , did you perform full rebuild of your project after adding the plugin? It's completely working fine in my case.

**Comment by justinmccombs** [comment]
I did, it looks like I missed the part where its only compatible with Android at the moment. Closing.

**Comment by sarbagyastha** [comment]
Support to iOS is added with this plugin [**youtube_player_flutter**](https://pub.dartlang.org/packages/youtube_player_flutter).
