### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method init on channel sarbagyastha.com.np/youtubePlayer)

### ISSUE THREAD

**Issue by lizhuoyuan** [sarbagyastha/youtube_player#25]
My project is Android mixed with Flutter, the Flutter project is dependent on the android project as a moudle, causing this problem:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel sarbagyastha.com.np/youtubePlayer)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
    <asynchronous suspension>
    #1      _channel (package:youtube_player/youtube_player.dart:17:9)
    #2      _channel (package:youtube_player/youtube_player.dart:15:21)
    #3      YoutubePlayer.keepOn (package:youtube_player/youtube_player.dart:745:36)
    #4      _YoutubePlayerState.build (package:youtube_player/youtube_player.dart:830:21)
    #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
    #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
    #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
    #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
    #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
    #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
    #12     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
    #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
    #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
    #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
    #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
    #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
    #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
    #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #23     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
    #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
    #25     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
    #26     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
    #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
    #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #30     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
    #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
    #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #34     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
    #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
    #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #38     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
    #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
    #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
    #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
    #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
    #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
    #44     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
    #45     Element.updateChild (package:flutter/src/widgets/fra
```

**Comment by sarbagyastha** [comment]
@lizhuoyuan , is this error on iOS ?

**Comment by lizhuoyuan** [comment]
Android

**Comment by sarbagyastha** [comment]
It's working perfectly fine in my case. Did you perform full build after adding the plugin ?

**Comment by lizhuoyuan** [comment]
yes , if I only run flutter project is ok , 
but when I run Android , it is wrong.
May be can you send me your project?
or update to github?

**Comment by sarbagyastha** [comment]
If you're directly using Android, then you could use official Youtube Player API for Android. This plugin is meant for Flutter only. What's your use case btw ?

**Comment by lizhuoyuan** [comment]
Thank you.
I done it use Android Youtube Player

**Comment by udi17live** [comment]
I get this same exception
