### ISSUE TITLE
Source error for ExoPlayerImplInternal

### ISSUE THREAD

**Issue by NhaPCS** [sarbagyastha/youtube_player#42]
I got the error when running some video like the following:

E/ExoPlayerImplInternal(22950): Source error.
E/ExoPlayerImplInternal(22950): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
E/ExoPlayerImplInternal(22950): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal(22950): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(22950): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(22950): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(22950): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/ExoPlayerImplInternal(22950): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/ExoPlayerImplInternal(22950): 	at java.lang.Thread.run(Thread.java:776)

Am I missing something? Please help me!

**Comment by sarbagyastha** [comment]
Could you provide me the videoId?

**Comment by NhaPCS** [comment]
It is Opoa-uxW7MQ
 Please check!

**Comment by sarbagyastha** [comment]
The plugin doesn't support some protected videos. It's kind of a limitation.

**Comment by SayaGames** [comment]
is there any method to catch the error ? (Your onError method can't catch the such error)

**Comment by daengweb** [comment]
I got some problems when isLive set to true. do you have solutions for these issues?

**Comment by valterh4ck3r** [comment]
Same problem

**Comment by valterh4ck3r** [comment]
> Could you provide me the videoId?

https://www.youtube.com/watch?v=JpgkVvePY2w 

Example above.

**Comment by baptisteArno** [comment]
> is there any method to catch the error ? (Your onError method can't catch the such error)

I'm looking for this too! Did you manage to do something about that?
