### ISSUE TITLE
Video not Playing

### ISSUE THREAD

**Issue by nitishpatel** [sarbagyastha/youtube_player#57]
CODE
`
YoutubePlayer(
            context: context,
            source: "https://www.youtube.com/watch?v=NHr6lTKYCNc",
            quality: YoutubeQuality.LOW,
            // callbackController is (optional).
            // use it to control player on your own.
            callbackController: (controller) {
              _videoController = controller;
            },
          )
,`
LOGS
```
I/ExoPlayerImpl( 7127): Release ab3bf3e [ExoPlayerLib/2.10.3] [generic_x86, Android SDK built for x86, Google, 29] [goog.exo.core]
I/flutter ( 7127): Youtube Video Id: NHr6lTKYCNc
D/SurfaceUtils( 7127): disconnecting from surface 0xb5269008, reason disconnectFromSurface
I/ExoPlayerImpl( 7127): Release bef8661 [ExoPlayerLib/2.10.3] [generic_x86, Android SDK built for x86, Google, 29] [goog.exo.core]
I/ExoPlayerImpl( 7127): Init 248760b [ExoPlayerLib/2.10.3] [generic_x86, Android SDK built for x86, Google, 29]
D/EGL_emulation( 7127): eglMakeCurrent: 0xbd84c760: ver 2 0 (tinfo 0xbed46900)
D/EGL_emulation( 7127): eglMakeCurrent: 0xbd84c760: ver 2 0 (tinfo 0xbed46900)
I/YoutubePlayerPlugin( 7127): Quality: 240p WEBM
I/YoutubePlayerPlugin( 7127): Media Type: GENERAL
I/le.syntechx_ap( 7127): Background young concurrent copying GC freed 58944(3151KB) AllocSpace objects, 17(1244KB) LOS objects, 26% free, 12MB/17MB, paused 7.057ms total 17.125ms
D/EGL_emulation( 7127): eglMakeCurrent: 0xbd84c760: ver 2 0 (tinfo 0xbed46900)
E/ExoPlayerImplInternal( 7127): Source error.
E/ExoPlayerImplInternal( 7127): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
E/ExoPlayerImplInternal( 7127):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:306)
E/ExoPlayerImplInternal( 7127):         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 7127):         at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
E/ExoPlayerImplInternal( 7127):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 7127):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 7127):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 7127):         at java.lang.Thread.run(Thread.java:919)
```

**Comment by SayaGames** [comment]
Did you try? source  source:NHr6lTKYCNc instead of "https://www.youtube.com/watch?v=NHr6lTKYCNc"
