### ISSUE TITLE
can't play video anymore

### ISSUE THREAD

**Issue by ayahsujana** [sarbagyastha/youtube_player#63]
this plugin can't play video from youtube again. can you solved this?

**Comment by silasrpg** [comment]
I wait or plugin to work again, I need to touch 4 random seconds of a video link.

**Comment by byambaa0111** [comment]
Hello. when i try to play youtube link it gives me error like this:

W/System.err(30546): java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
W/System.err(30546): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err(30546): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W/System.err(30546): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
W/System.err(30546): 	at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:469)
W/System.err(30546): 	at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:409)
W/System.err(30546): 	at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:200)
W/System.err(30546): 	at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:35)
W/System.err(30546): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err(30546): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(30546): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err(30546): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(30546): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(30546): 	at java.lang.Thread.run(Thread.java:764)

**Comment by yasintz** [comment]
@sarbagyastha
