### ISSUE TITLE
Access denied finding property "persist.report.tid"

### ISSUE THREAD

**Issue by iam-febriansyah** [sarbagyastha/youtube_player#67]
Hallo flutter's
I have the issue : 

Access denied finding property "persist.report.tid"
I/ExoPlayerImpl(24503): Init 28fea41 [ExoPlayerLib/2.10.3] [RMX1903, RMX1903, Realme, 29]
I/flutter (24503): 1
I/ple.portal_des(24503): ProcessProfilingInfo new_methods=59 is saved saved_to_disk=1 resolve_classes_delay=5000
W/System.err(24503): java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
W/System.err(24503):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err(24503):    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/System.err(24503):    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:479)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:419)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:202)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:35)
W/System.err(24503):    at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err(24503):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(24503):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err(24503):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(24503):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(24503):    at java.lang.Thread.run(Thread.java:919)
W/System.err(24503): java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
W/System.err(24503):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err(24503):    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/System.err(24503):    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:479)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:419)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:202)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:35)
W/System.err(24503):    at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err(24503):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(24503):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err(24503):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(24503):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(24503):    at java.lang.Thread.run(Thread.java:919)
W/System.err(24503): java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
W/System.err(24503):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err(24503):    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/System.err(24503):    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:479)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:419)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:202)
W/System.err(24503):    at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:35)
W/System.err(24503):    at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err(24503):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(24503):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err(24503):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(24503):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(24503):    at java.lang.Thread.run(Thread.java:919)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

Please help me to fix it with the error  :')

**Comment by sidkhore1002** [comment]
Any solution?
